createBasicMaxDiffFile <- function()
{
     sink("ExampleBasicMaxDiff.R",append=F)
     cat("# ------------------","\n")
     cat("# Code for a MaxDiff (Best Worst Scaling) Multinomial Logit Model with Random Coefficients","\n")
     cat("# ","\n")
     cat("# Jeff Dumont","\n")
     cat("#","\n")
     cat("# Requires","\n")
     cat("# data.table package","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("library(RSGHB)","\n")
     cat("library(data.table)","\n")
     cat("","\n")
     cat("createGlobalVariables()","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# Global Settings","\n")
     cat("# ------------------","\n")
     cat("setwd(\"C:/Work/Code/HB/Examples/Basic Example - MaxDiff\" # working directory","\n")
     cat("modelname <- \"MD1_Base\"			# used for output","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# DATA ","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("choicedata <- read.table(\"MD_forRSGHB.txt\",sep=\"\t\",header=T)","\n")
     cat("","\n")
     cat("# The attributes","\n")
     cat("id = choicedata$id","\n")
     cat("thecount = choicedata$thecount","\n")
     cat("choice = choicedata$Choice","\n")
     cat("alt_1statement1  = choicedata$alt_1statement1","\n")
     cat("alt_1statement2  = choicedata$alt_1statement2","\n")
     cat("alt_1statement3  = choicedata$alt_1statement3","\n")
     cat("alt_1statement4  = choicedata$alt_1statement4","\n")
     cat("alt_1statement5  = choicedata$alt_1statement5","\n")
     cat("alt_1statement6  = choicedata$alt_1statement6","\n")
     cat("alt_1statement7  = choicedata$alt_1statement7","\n")
     cat("alt_1statement8  = choicedata$alt_1statement8","\n")
     cat("alt_1statement9  = choicedata$alt_1statement9","\n")
     cat("alt_1statement10 = choicedata$alt_1statement10","\n")
     cat("alt_1statement11 = choicedata$alt_1statement11","\n")
     cat("alt_1statement12 = choicedata$alt_1statement12","\n")
     cat("alt_1statement13 = choicedata$alt_1statement13","\n")
     cat("alt_1statement14 = choicedata$alt_1statement14","\n")
     cat("alt_1statement15 = choicedata$alt_1statement15","\n")
     cat("alt_1statement16 = choicedata$alt_1statement16","\n")
     cat("alt_1statement17 = choicedata$alt_1statement17","\n")
     cat("alt_1statement18 = choicedata$alt_1statement18","\n")
     cat("alt_1statement19 = choicedata$alt_1statement19","\n")
     cat("alt_1statement20 = choicedata$alt_1statement20","\n")
     cat("alt_1statement21 = choicedata$alt_1statement21","\n")
     cat("alt_1statement22 = choicedata$alt_1statement22","\n")
     cat("alt_1statement23 = choicedata$alt_1statement23","\n")
     cat("alt_1statement24 = choicedata$alt_1statement24","\n")
     cat("alt_1statement25 = choicedata$alt_1statement25","\n")
     cat("alt_1statement26 = choicedata$alt_1statement26","\n")
     cat("alt_1statement27 = choicedata$alt_1statement27","\n")
     cat("alt_1statement28 = choicedata$alt_1statement28","\n")
     cat("alt_1statement29 = choicedata$alt_1statement29","\n")
     cat("alt_1statement30 = choicedata$alt_1statement30","\n")
     cat("alt_1statement31 = choicedata$alt_1statement31","\n")
     cat("alt_2statement1 = choicedata$alt_2statement1","\n")
     cat("alt_2statement2 = choicedata$alt_2statement2","\n")
     cat("alt_2statement3 = choicedata$alt_2statement3","\n")
     cat("alt_2statement4 = choicedata$alt_2statement4","\n")
     cat("alt_2statement5 = choicedata$alt_2statement5","\n")
     cat("alt_2statement6 = choicedata$alt_2statement6","\n")
     cat("alt_2statement7 = choicedata$alt_2statement7","\n")
     cat("alt_2statement8 = choicedata$alt_2statement8","\n")
     cat("alt_2statement9 = choicedata$alt_2statement9","\n")
     cat("alt_2statement10 = choicedata$alt_2statement10","\n")
     cat("alt_2statement11 = choicedata$alt_2statement11","\n")
     cat("alt_2statement12 = choicedata$alt_2statement12","\n")
     cat("alt_2statement13 = choicedata$alt_2statement13","\n")
     cat("alt_2statement14 = choicedata$alt_2statement14","\n")
     cat("alt_2statement15 = choicedata$alt_2statement15","\n")
     cat("alt_2statement16 = choicedata$alt_2statement16","\n")
     cat("alt_2statement17 = choicedata$alt_2statement17","\n")
     cat("alt_2statement18 = choicedata$alt_2statement18","\n")
     cat("alt_2statement19 = choicedata$alt_2statement19","\n")
     cat("alt_2statement20 = choicedata$alt_2statement20","\n")
     cat("alt_2statement21 = choicedata$alt_2statement21","\n")
     cat("alt_2statement22 = choicedata$alt_2statement22","\n")
     cat("alt_2statement23 = choicedata$alt_2statement23","\n")
     cat("alt_2statement24 = choicedata$alt_2statement24","\n")
     cat("alt_2statement25 = choicedata$alt_2statement25","\n")
     cat("alt_2statement26 = choicedata$alt_2statement26","\n")
     cat("alt_2statement27 = choicedata$alt_2statement27","\n")
     cat("alt_2statement28 = choicedata$alt_2statement28","\n")
     cat("alt_2statement29 = choicedata$alt_2statement29","\n")
     cat("alt_2statement30 = choicedata$alt_2statement30","\n")
     cat("alt_2statement31 = choicedata$alt_2statement31","\n")
     cat("alt_3statement1 = choicedata$alt_3statement1","\n")
     cat("alt_3statement2 = choicedata$alt_3statement2","\n")
     cat("alt_3statement3 = choicedata$alt_3statement3","\n")
     cat("alt_3statement4 = choicedata$alt_3statement4","\n")
     cat("alt_3statement5 = choicedata$alt_3statement5","\n")
     cat("alt_3statement6 = choicedata$alt_3statement6","\n")
     cat("alt_3statement7 = choicedata$alt_3statement7","\n")
     cat("alt_3statement8 = choicedata$alt_3statement8","\n")
     cat("alt_3statement9 = choicedata$alt_3statement9","\n")
     cat("alt_3statement10 = choicedata$alt_3statement10","\n")
     cat("alt_3statement11 = choicedata$alt_3statement11","\n")
     cat("alt_3statement12 = choicedata$alt_3statement12","\n")
     cat("alt_3statement13 = choicedata$alt_3statement13","\n")
     cat("alt_3statement14 = choicedata$alt_3statement14","\n")
     cat("alt_3statement15 = choicedata$alt_3statement15","\n")
     cat("alt_3statement16 = choicedata$alt_3statement16","\n")
     cat("alt_3statement17 = choicedata$alt_3statement17","\n")
     cat("alt_3statement18 = choicedata$alt_3statement18","\n")
     cat("alt_3statement19 = choicedata$alt_3statement19","\n")
     cat("alt_3statement20 = choicedata$alt_3statement20","\n")
     cat("alt_3statement21 = choicedata$alt_3statement21","\n")
     cat("alt_3statement22 = choicedata$alt_3statement22","\n")
     cat("alt_3statement23 = choicedata$alt_3statement23","\n")
     cat("alt_3statement24 = choicedata$alt_3statement24","\n")
     cat("alt_3statement25 = choicedata$alt_3statement25","\n")
     cat("alt_3statement26 = choicedata$alt_3statement26","\n")
     cat("alt_3statement27 = choicedata$alt_3statement27","\n")
     cat("alt_3statement28 = choicedata$alt_3statement28","\n")
     cat("alt_3statement29 = choicedata$alt_3statement29","\n")
     cat("alt_3statement30 = choicedata$alt_3statement30","\n")
     cat("alt_3statement31 = choicedata$alt_3statement31","\n")
     cat("alt_4statement1 = choicedata$alt_4statement1","\n")
     cat("alt_4statement2 = choicedata$alt_4statement2","\n")
     cat("alt_4statement3 = choicedata$alt_4statement3","\n")
     cat("alt_4statement4 = choicedata$alt_4statement4","\n")
     cat("alt_4statement5 = choicedata$alt_4statement5","\n")
     cat("alt_4statement6 = choicedata$alt_4statement6","\n")
     cat("alt_4statement7 = choicedata$alt_4statement7","\n")
     cat("alt_4statement8 = choicedata$alt_4statement8","\n")
     cat("alt_4statement9 = choicedata$alt_4statement9","\n")
     cat("alt_4statement10 = choicedata$alt_4statement10","\n")
     cat("alt_4statement11 = choicedata$alt_4statement11","\n")
     cat("alt_4statement12 = choicedata$alt_4statement12","\n")
     cat("alt_4statement13 = choicedata$alt_4statement13","\n")
     cat("alt_4statement14 = choicedata$alt_4statement14","\n")
     cat("alt_4statement15 = choicedata$alt_4statement15","\n")
     cat("alt_4statement16 = choicedata$alt_4statement16","\n")
     cat("alt_4statement17 = choicedata$alt_4statement17","\n")
     cat("alt_4statement18 = choicedata$alt_4statement18","\n")
     cat("alt_4statement19 = choicedata$alt_4statement19","\n")
     cat("alt_4statement20 = choicedata$alt_4statement20","\n")
     cat("alt_4statement21 = choicedata$alt_4statement21","\n")
     cat("alt_4statement22 = choicedata$alt_4statement22","\n")
     cat("alt_4statement23 = choicedata$alt_4statement23","\n")
     cat("alt_4statement24 = choicedata$alt_4statement24","\n")
     cat("alt_4statement25 = choicedata$alt_4statement25","\n")
     cat("alt_4statement26 = choicedata$alt_4statement26","\n")
     cat("alt_4statement27 = choicedata$alt_4statement27","\n")
     cat("alt_4statement28 = choicedata$alt_4statement28","\n")
     cat("alt_4statement29 = choicedata$alt_4statement29","\n")
     cat("alt_4statement30 = choicedata$alt_4statement30","\n")
     cat("alt_4statement31 = choicedata$alt_4statement31","\n")
     cat("alt_5statement1 = choicedata$alt_5statement1","\n")
     cat("alt_5statement2 = choicedata$alt_5statement2","\n")
     cat("alt_5statement3 = choicedata$alt_5statement3","\n")
     cat("alt_5statement4 = choicedata$alt_5statement4","\n")
     cat("alt_5statement5 = choicedata$alt_5statement5","\n")
     cat("alt_5statement6 = choicedata$alt_5statement6","\n")
     cat("alt_5statement7 = choicedata$alt_5statement7","\n")
     cat("alt_5statement8 = choicedata$alt_5statement8","\n")
     cat("alt_5statement9 = choicedata$alt_5statement9","\n")
     cat("alt_5statement10 = choicedata$alt_5statement10","\n")
     cat("alt_5statement11 = choicedata$alt_5statement11","\n")
     cat("alt_5statement12 = choicedata$alt_5statement12","\n")
     cat("alt_5statement13 = choicedata$alt_5statement13","\n")
     cat("alt_5statement14 = choicedata$alt_5statement14","\n")
     cat("alt_5statement15 = choicedata$alt_5statement15","\n")
     cat("alt_5statement16 = choicedata$alt_5statement16","\n")
     cat("alt_5statement17 = choicedata$alt_5statement17","\n")
     cat("alt_5statement18 = choicedata$alt_5statement18","\n")
     cat("alt_5statement19 = choicedata$alt_5statement19","\n")
     cat("alt_5statement20 = choicedata$alt_5statement20","\n")
     cat("alt_5statement21 = choicedata$alt_5statement21","\n")
     cat("alt_5statement22 = choicedata$alt_5statement22","\n")
     cat("alt_5statement23 = choicedata$alt_5statement23","\n")
     cat("alt_5statement24 = choicedata$alt_5statement24","\n")
     cat("alt_5statement25 = choicedata$alt_5statement25","\n")
     cat("alt_5statement26 = choicedata$alt_5statement26","\n")
     cat("alt_5statement27 = choicedata$alt_5statement27","\n")
     cat("alt_5statement28 = choicedata$alt_5statement28","\n")
     cat("alt_5statement29 = choicedata$alt_5statement29","\n")
     cat("alt_5statement30 = choicedata$alt_5statement30","\n")
     cat("alt_5statement31 = choicedata$alt_5statement31","\n")
     cat("alt_6statement1 = choicedata$alt_6statement1","\n")
     cat("alt_6statement2 = choicedata$alt_6statement2","\n")
     cat("alt_6statement3 = choicedata$alt_6statement3","\n")
     cat("alt_6statement4 = choicedata$alt_6statement4","\n")
     cat("alt_6statement5 = choicedata$alt_6statement5","\n")
     cat("alt_6statement6 = choicedata$alt_6statement6","\n")
     cat("alt_6statement7 = choicedata$alt_6statement7","\n")
     cat("alt_6statement8 = choicedata$alt_6statement8","\n")
     cat("alt_6statement9 = choicedata$alt_6statement9","\n")
     cat("alt_6statement10 = choicedata$alt_6statement10","\n")
     cat("alt_6statement11 = choicedata$alt_6statement11","\n")
     cat("alt_6statement12 = choicedata$alt_6statement12","\n")
     cat("alt_6statement13 = choicedata$alt_6statement13","\n")
     cat("alt_6statement14 = choicedata$alt_6statement14","\n")
     cat("alt_6statement15 = choicedata$alt_6statement15","\n")
     cat("alt_6statement16 = choicedata$alt_6statement16","\n")
     cat("alt_6statement17 = choicedata$alt_6statement17","\n")
     cat("alt_6statement18 = choicedata$alt_6statement18","\n")
     cat("alt_6statement19 = choicedata$alt_6statement19","\n")
     cat("alt_6statement20 = choicedata$alt_6statement20","\n")
     cat("alt_6statement21 = choicedata$alt_6statement21","\n")
     cat("alt_6statement22 = choicedata$alt_6statement22","\n")
     cat("alt_6statement23 = choicedata$alt_6statement23","\n")
     cat("alt_6statement24 = choicedata$alt_6statement24","\n")
     cat("alt_6statement25 = choicedata$alt_6statement25","\n")
     cat("alt_6statement26 = choicedata$alt_6statement26","\n")
     cat("alt_6statement27 = choicedata$alt_6statement27","\n")
     cat("alt_6statement28 = choicedata$alt_6statement28","\n")
     cat("alt_6statement29 = choicedata$alt_6statement29","\n")
     cat("alt_6statement30 = choicedata$alt_6statement30","\n")
     cat("alt_6statement31 = choicedata$alt_6statement31","\n")
     cat("alt_7statement1 = choicedata$alt_7statement1","\n")
     cat("alt_7statement2 = choicedata$alt_7statement2","\n")
     cat("alt_7statement3 = choicedata$alt_7statement3","\n")
     cat("alt_7statement4 = choicedata$alt_7statement4","\n")
     cat("alt_7statement5 = choicedata$alt_7statement5","\n")
     cat("alt_7statement6 = choicedata$alt_7statement6","\n")
     cat("alt_7statement7 = choicedata$alt_7statement7","\n")
     cat("alt_7statement8 = choicedata$alt_7statement8","\n")
     cat("alt_7statement9 = choicedata$alt_7statement9","\n")
     cat("alt_7statement10 = choicedata$alt_7statement10","\n")
     cat("alt_7statement11 = choicedata$alt_7statement11","\n")
     cat("alt_7statement12 = choicedata$alt_7statement12","\n")
     cat("alt_7statement13 = choicedata$alt_7statement13","\n")
     cat("alt_7statement14 = choicedata$alt_7statement14","\n")
     cat("alt_7statement15 = choicedata$alt_7statement15","\n")
     cat("alt_7statement16 = choicedata$alt_7statement16","\n")
     cat("alt_7statement17 = choicedata$alt_7statement17","\n")
     cat("alt_7statement18 = choicedata$alt_7statement18","\n")
     cat("alt_7statement19 = choicedata$alt_7statement19","\n")
     cat("alt_7statement20 = choicedata$alt_7statement20","\n")
     cat("alt_7statement21 = choicedata$alt_7statement21","\n")
     cat("alt_7statement22 = choicedata$alt_7statement22","\n")
     cat("alt_7statement23 = choicedata$alt_7statement23","\n")
     cat("alt_7statement24 = choicedata$alt_7statement24","\n")
     cat("alt_7statement25 = choicedata$alt_7statement25","\n")
     cat("alt_7statement26 = choicedata$alt_7statement26","\n")
     cat("alt_7statement27 = choicedata$alt_7statement27","\n")
     cat("alt_7statement28 = choicedata$alt_7statement28","\n")
     cat("alt_7statement29 = choicedata$alt_7statement29","\n")
     cat("alt_7statement30 = choicedata$alt_7statement30","\n")
     cat("alt_7statement31 = choicedata$alt_7statement31","\n")
     cat("alt_8statement1 = choicedata$alt_8statement1","\n")
     cat("alt_8statement2 = choicedata$alt_8statement2","\n")
     cat("alt_8statement3 = choicedata$alt_8statement3","\n")
     cat("alt_8statement4 = choicedata$alt_8statement4","\n")
     cat("alt_8statement5 = choicedata$alt_8statement5","\n")
     cat("alt_8statement6 = choicedata$alt_8statement6","\n")
     cat("alt_8statement7 = choicedata$alt_8statement7","\n")
     cat("alt_8statement8 = choicedata$alt_8statement8","\n")
     cat("alt_8statement9 = choicedata$alt_8statement9","\n")
     cat("alt_8statement10 = choicedata$alt_8statement10","\n")
     cat("alt_8statement11 = choicedata$alt_8statement11","\n")
     cat("alt_8statement12 = choicedata$alt_8statement12","\n")
     cat("alt_8statement13 = choicedata$alt_8statement13","\n")
     cat("alt_8statement14 = choicedata$alt_8statement14","\n")
     cat("alt_8statement15 = choicedata$alt_8statement15","\n")
     cat("alt_8statement16 = choicedata$alt_8statement16","\n")
     cat("alt_8statement17 = choicedata$alt_8statement17","\n")
     cat("alt_8statement18 = choicedata$alt_8statement18","\n")
     cat("alt_8statement19 = choicedata$alt_8statement19","\n")
     cat("alt_8statement20 = choicedata$alt_8statement20","\n")
     cat("alt_8statement21 = choicedata$alt_8statement21","\n")
     cat("alt_8statement22 = choicedata$alt_8statement22","\n")
     cat("alt_8statement23 = choicedata$alt_8statement23","\n")
     cat("alt_8statement24 = choicedata$alt_8statement24","\n")
     cat("alt_8statement25 = choicedata$alt_8statement25","\n")
     cat("alt_8statement26 = choicedata$alt_8statement26","\n")
     cat("alt_8statement27 = choicedata$alt_8statement27","\n")
     cat("alt_8statement28 = choicedata$alt_8statement28","\n")
     cat("alt_8statement29 = choicedata$alt_8statement29","\n")
     cat("alt_8statement30 = choicedata$alt_8statement30","\n")
     cat("alt_8statement31 = choicedata$alt_8statement31","\n")
     cat("alt_9statement1 = choicedata$alt_9statement1","\n")
     cat("alt_9statement2 = choicedata$alt_9statement2","\n")
     cat("alt_9statement3 = choicedata$alt_9statement3","\n")
     cat("alt_9statement4 = choicedata$alt_9statement4","\n")
     cat("alt_9statement5 = choicedata$alt_9statement5","\n")
     cat("alt_9statement6 = choicedata$alt_9statement6","\n")
     cat("alt_9statement7 = choicedata$alt_9statement7","\n")
     cat("alt_9statement8 = choicedata$alt_9statement8","\n")
     cat("alt_9statement9 = choicedata$alt_9statement9","\n")
     cat("alt_9statement10 = choicedata$alt_9statement10","\n")
     cat("alt_9statement11 = choicedata$alt_9statement11","\n")
     cat("alt_9statement12 = choicedata$alt_9statement12","\n")
     cat("alt_9statement13 = choicedata$alt_9statement13","\n")
     cat("alt_9statement14 = choicedata$alt_9statement14","\n")
     cat("alt_9statement15 = choicedata$alt_9statement15","\n")
     cat("alt_9statement16 = choicedata$alt_9statement16","\n")
     cat("alt_9statement17 = choicedata$alt_9statement17","\n")
     cat("alt_9statement18 = choicedata$alt_9statement18","\n")
     cat("alt_9statement19 = choicedata$alt_9statement19","\n")
     cat("alt_9statement20 = choicedata$alt_9statement20","\n")
     cat("alt_9statement21 = choicedata$alt_9statement21","\n")
     cat("alt_9statement22 = choicedata$alt_9statement22","\n")
     cat("alt_9statement23 = choicedata$alt_9statement23","\n")
     cat("alt_9statement24 = choicedata$alt_9statement24","\n")
     cat("alt_9statement25 = choicedata$alt_9statement25","\n")
     cat("alt_9statement26 = choicedata$alt_9statement26","\n")
     cat("alt_9statement27 = choicedata$alt_9statement27","\n")
     cat("alt_9statement28 = choicedata$alt_9statement28","\n")
     cat("alt_9statement29 = choicedata$alt_9statement29","\n")
     cat("alt_9statement30 = choicedata$alt_9statement30","\n")
     cat("alt_9statement31 = choicedata$alt_9statement31","\n")
     cat("alt_10statement1 = choicedata$alt_10statement1","\n")
     cat("alt_10statement2 = choicedata$alt_10statement2","\n")
     cat("alt_10statement3 = choicedata$alt_10statement3","\n")
     cat("alt_10statement4 = choicedata$alt_10statement4","\n")
     cat("alt_10statement5 = choicedata$alt_10statement5","\n")
     cat("alt_10statement6 = choicedata$alt_10statement6","\n")
     cat("alt_10statement7 = choicedata$alt_10statement7","\n")
     cat("alt_10statement8 = choicedata$alt_10statement8","\n")
     cat("alt_10statement9 = choicedata$alt_10statement9","\n")
     cat("alt_10statement10 = choicedata$alt_10statement10","\n")
     cat("alt_10statement11 = choicedata$alt_10statement11","\n")
     cat("alt_10statement12 = choicedata$alt_10statement12","\n")
     cat("alt_10statement13 = choicedata$alt_10statement13","\n")
     cat("alt_10statement14 = choicedata$alt_10statement14","\n")
     cat("alt_10statement15 = choicedata$alt_10statement15","\n")
     cat("alt_10statement16 = choicedata$alt_10statement16","\n")
     cat("alt_10statement17 = choicedata$alt_10statement17","\n")
     cat("alt_10statement18 = choicedata$alt_10statement18","\n")
     cat("alt_10statement19 = choicedata$alt_10statement19","\n")
     cat("alt_10statement20 = choicedata$alt_10statement20","\n")
     cat("alt_10statement21 = choicedata$alt_10statement21","\n")
     cat("alt_10statement22 = choicedata$alt_10statement22","\n")
     cat("alt_10statement23 = choicedata$alt_10statement23","\n")
     cat("alt_10statement24 = choicedata$alt_10statement24","\n")
     cat("alt_10statement25 = choicedata$alt_10statement25","\n")
     cat("alt_10statement26 = choicedata$alt_10statement26","\n")
     cat("alt_10statement27 = choicedata$alt_10statement27","\n")
     cat("alt_10statement28 = choicedata$alt_10statement28","\n")
     cat("alt_10statement29 = choicedata$alt_10statement29","\n")
     cat("alt_10statement30 = choicedata$alt_10statement30","\n")
     cat("alt_10statement31 = choicedata$alt_10statement31","\n")
     cat("alt_11statement1 = choicedata$alt_11statement1","\n")
     cat("alt_11statement2 = choicedata$alt_11statement2","\n")
     cat("alt_11statement3 = choicedata$alt_11statement3","\n")
     cat("alt_11statement4 = choicedata$alt_11statement4","\n")
     cat("alt_11statement5 = choicedata$alt_11statement5","\n")
     cat("alt_11statement6 = choicedata$alt_11statement6","\n")
     cat("alt_11statement7 = choicedata$alt_11statement7","\n")
     cat("alt_11statement8 = choicedata$alt_11statement8","\n")
     cat("alt_11statement9 = choicedata$alt_11statement9","\n")
     cat("alt_11statement10 = choicedata$alt_11statement10","\n")
     cat("alt_11statement11 = choicedata$alt_11statement11","\n")
     cat("alt_11statement12 = choicedata$alt_11statement12","\n")
     cat("alt_11statement13 = choicedata$alt_11statement13","\n")
     cat("alt_11statement14 = choicedata$alt_11statement14","\n")
     cat("alt_11statement15 = choicedata$alt_11statement15","\n")
     cat("alt_11statement16 = choicedata$alt_11statement16","\n")
     cat("alt_11statement17 = choicedata$alt_11statement17","\n")
     cat("alt_11statement18 = choicedata$alt_11statement18","\n")
     cat("alt_11statement19 = choicedata$alt_11statement19","\n")
     cat("alt_11statement20 = choicedata$alt_11statement20","\n")
     cat("alt_11statement21 = choicedata$alt_11statement21","\n")
     cat("alt_11statement22 = choicedata$alt_11statement22","\n")
     cat("alt_11statement23 = choicedata$alt_11statement23","\n")
     cat("alt_11statement24 = choicedata$alt_11statement24","\n")
     cat("alt_11statement25 = choicedata$alt_11statement25","\n")
     cat("alt_11statement26 = choicedata$alt_11statement26","\n")
     cat("alt_11statement27 = choicedata$alt_11statement27","\n")
     cat("alt_11statement28 = choicedata$alt_11statement28","\n")
     cat("alt_11statement29 = choicedata$alt_11statement29","\n")
     cat("alt_11statement30 = choicedata$alt_11statement30","\n")
     cat("alt_11statement31 = choicedata$alt_11statement31","\n")
     cat("alt_12statement1 = choicedata$alt_12statement1","\n")
     cat("alt_12statement2 = choicedata$alt_12statement2","\n")
     cat("alt_12statement3 = choicedata$alt_12statement3","\n")
     cat("alt_12statement4 = choicedata$alt_12statement4","\n")
     cat("alt_12statement5 = choicedata$alt_12statement5","\n")
     cat("alt_12statement6 = choicedata$alt_12statement6","\n")
     cat("alt_12statement7 = choicedata$alt_12statement7","\n")
     cat("alt_12statement8 = choicedata$alt_12statement8","\n")
     cat("alt_12statement9 = choicedata$alt_12statement9","\n")
     cat("alt_12statement10 = choicedata$alt_12statement10","\n")
     cat("alt_12statement11 = choicedata$alt_12statement11","\n")
     cat("alt_12statement12 = choicedata$alt_12statement12","\n")
     cat("alt_12statement13 = choicedata$alt_12statement13","\n")
     cat("alt_12statement14 = choicedata$alt_12statement14","\n")
     cat("alt_12statement15 = choicedata$alt_12statement15","\n")
     cat("alt_12statement16 = choicedata$alt_12statement16","\n")
     cat("alt_12statement17 = choicedata$alt_12statement17","\n")
     cat("alt_12statement18 = choicedata$alt_12statement18","\n")
     cat("alt_12statement19 = choicedata$alt_12statement19","\n")
     cat("alt_12statement20 = choicedata$alt_12statement20","\n")
     cat("alt_12statement21 = choicedata$alt_12statement21","\n")
     cat("alt_12statement22 = choicedata$alt_12statement22","\n")
     cat("alt_12statement23 = choicedata$alt_12statement23","\n")
     cat("alt_12statement24 = choicedata$alt_12statement24","\n")
     cat("alt_12statement25 = choicedata$alt_12statement25","\n")
     cat("alt_12statement26 = choicedata$alt_12statement26","\n")
     cat("alt_12statement27 = choicedata$alt_12statement27","\n")
     cat("alt_12statement28 = choicedata$alt_12statement28","\n")
     cat("alt_12statement29 = choicedata$alt_12statement29","\n")
     cat("alt_12statement30 = choicedata$alt_12statement30","\n")
     cat("alt_12statement31 = choicedata$alt_12statement31","\n")
     cat("","\n")
     cat("# The choice vectors","\n")
     cat("choice1  <- (choice==1) ","\n")
     cat("choice2  <- (choice==2) ","\n")
     cat("choice3  <- (choice==3) ","\n")
     cat("choice4  <- (choice==4) ","\n")
     cat("choice5  <- (choice==5) ","\n")
     cat("choice6  <- (choice==6) ","\n")
     cat("choice7  <- (choice==7) ","\n")
     cat("choice8  <- (choice==8) ","\n")
     cat("choice9  <- (choice==9) ","\n")
     cat("choice10 <- (choice==10)","\n")
     cat("choice11 <- (choice==11)","\n")
     cat("choice12 <- (choice==12)","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# MODEL SPECIFICATION ","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("gVarNamesNormal <- c(","\n")
     cat("     \"U_2\",","\n")
     cat("     \"U_3\",","\n")
     cat("     \"U_4\",","\n")
     cat("     \"U_5\",","\n")
     cat("     \"U_6\",","\n")
     cat("     \"U_7\",","\n")
     cat("     \"U_8\",","\n")
     cat("     \"U_9\",","\n")
     cat("     \"U_10\",","\n")
     cat("     \"U_11\",","\n")
     cat("     \"U_12\",","\n")
     cat("     \"U_13\",","\n")
     cat("     \"U_14\",","\n")
     cat("     \"U_15\",","\n")
     cat("     \"U_16\",","\n")
     cat("     \"U_17\",","\n")
     cat("     \"U_18\",","\n")
     cat("     \"U_19\",","\n")
     cat("     \"U_20\",","\n")
     cat("     \"U_21\",","\n")
     cat("     \"U_22\",","\n")
     cat("     \"U_23\",","\n")
     cat("     \"U_24\",","\n")
     cat("     \"U_25\",","\n")
     cat("     \"U_26\",","\n")
     cat("     \"U_27\",","\n")
     cat("     \"U_28\",","\n")
     cat("     \"U_29\",","\n")
     cat("     \"U_30\",","\n")
     cat("     \"U_31\",","\n")
     cat("     \"asc_2\",","\n")
     cat("     \"asc_3\",","\n")
     cat("     \"asc_4\",","\n")
     cat("     \"asc_5\",","\n")
     cat("     \"asc_6\",","\n")
     cat("     \"asc_7\",","\n")
     cat("     \"asc_8\",","\n")
     cat("     \"asc_9\",","\n")
     cat("     \"asc_10\",","\n")
     cat("     \"asc_11\",","\n")
     cat("     \"asc_12\")","\n")
     cat("","\n")
     cat("gVarNamesFixed <- c()","\n")
     cat("","\n")
     cat("# For each variable, specify the distribution for its coefficient","\n")
     cat("# The options are:","\n")
     cat("# 1. normal","\n")
     cat("# 2. log-nomal","\n")
     cat("# 3. negative log-normal","\n")
     cat("# 4. normal with all values below zero massed at zero","\n")
     cat("# 5. Johnson SB with a specified min and max","\n")
     cat("# gDIST must have NIV elements","\n")
     cat("","\n")
     cat("gDIST <- c(rep(1,length(gVarNamesNormal)))","\n")
     cat("","\n")
     cat("# If any element of gDIST is 5, then you must specify the max and min","\n")
     cat("# for that coefficient. MIN and MAX each has NIV elements. ","\n")
     cat("# Only the elements tat correspond to a 5 in gDIST are used. However,","\n")
     cat("# all elements must be given real numbers","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# STARTING VALUES","\n")
     cat("# ------------------","\n")
     cat("FC <- c()                  # for the fixed coefficients","\n")
     cat("","\n")
     cat("svN <- c(0,0,0)            # for the random coefficients","\n")
     cat("                           # The selection of the mean here is important when working with non-normal distributions","\n")
     cat("# ------------------","\n")
     cat("# ITERATION SETTINGS","\n")
     cat("# ------------------","\n")
     cat("gNCREP    <- 20000  	  # Number of iterations to use prior to convergence","\n")
     cat("gNEREP    <- 10000 	       # Number of iterations to keep for averaging after convergence has been reached","\n")
     cat("gNSKIP    <- 1			  # Number of iterations to do in between retaining draws for averaging","\n")
     cat("gINFOSKIP <- 250           # How frequently to print info about the iteration process","\n")
     cat("","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# likelihood		","\n")
     cat("# USE:     Calculates the likelihood of choice | B","\n")
     cat("#          Returns individual-specific likelihood values","\n")
     cat("# NOTES:   This is where the bulk of the computation resides so coding this efficiently","\n")
     cat("#	      is essential to reducing run time.","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("likelihood <- function(fc,b)","\n")
     cat("{","\n")
     cat("     ","\n")
     cat("     C      <- trans(b)","\n")
     cat("     ","\n")
     cat("     # creates vectors of individual-specific coefficients","\n")
     cat("     cc<-1","\n")
     cat("     U_1=0","\n")
     cat("     U_2=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_3=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_4=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_5=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_6=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_7=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_8=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_9=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_10=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_11=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_12=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_13=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_14=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_15=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_16=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_17=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_18=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_19=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_20=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_21=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_22=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_23=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_24=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_25=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_26=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_27=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_28=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_29=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_30=C[gIDS,cc];cc<-cc+1","\n")
     cat("     U_31=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_1=0","\n")
     cat("     asc_2=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_3=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_4=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_5=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_6=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_7=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_8=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_9=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_10=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_11=C[gIDS,cc];cc<-cc+1","\n")
     cat("     asc_12=C[gIDS,cc];cc<-cc+1","\n")
     cat("     ","\n")
     cat("     v1    = 	asc_1  + U_1 * alt_1statement1	 + U_2 * alt_1statement2	 + U_3 * alt_1statement3	 + U_4 * alt_1statement4	 + U_5 * alt_1statement5	 + U_6 * alt_1statement6	 + U_7 * alt_1statement7	 + U_8 * alt_1statement8	 + U_9 * alt_1statement9	 + U_10 * alt_1statement10	 + U_11 * alt_1statement11	 + U_12 * alt_1statement12	 + U_13 * alt_1statement13	 + U_14 * alt_1statement14	 + U_15 * alt_1statement15	 + U_16 * alt_1statement16	 + U_17 * alt_1statement17	 + U_18 * alt_1statement18	 + U_19 * alt_1statement19	 + U_20 * alt_1statement20	 + U_21 * alt_1statement21	 + U_22 * alt_1statement22	 + U_23 * alt_1statement23	 + U_24 * alt_1statement24	 + U_25 * alt_1statement25	 + U_26 * alt_1statement26	 + U_27 * alt_1statement27	 + U_28 * alt_1statement28	 + U_29 * alt_1statement29	 + U_30 * alt_1statement30	 + U_31 * alt_1statement31	 ","\n")
     cat("     v2	= 	asc_2  + U_1 * alt_2statement1	 + U_2 * alt_2statement2	 + U_3 * alt_2statement3	 + U_4 * alt_2statement4	 + U_5 * alt_2statement5	 + U_6 * alt_2statement6	 + U_7 * alt_2statement7	 + U_8 * alt_2statement8	 + U_9 * alt_2statement9	 + U_10 * alt_2statement10	 + U_11 * alt_2statement11	 + U_12 * alt_2statement12	 + U_13 * alt_2statement13	 + U_14 * alt_2statement14	 + U_15 * alt_2statement15	 + U_16 * alt_2statement16	 + U_17 * alt_2statement17	 + U_18 * alt_2statement18	 + U_19 * alt_2statement19	 + U_20 * alt_2statement20	 + U_21 * alt_2statement21	 + U_22 * alt_2statement22	 + U_23 * alt_2statement23	 + U_24 * alt_2statement24	 + U_25 * alt_2statement25	 + U_26 * alt_2statement26	 + U_27 * alt_2statement27	 + U_28 * alt_2statement28	 + U_29 * alt_2statement29	 + U_30 * alt_2statement30	 + U_31 * alt_2statement31	 ","\n")
     cat("     v3	= 	asc_3  + U_1 * alt_3statement1	 + U_2 * alt_3statement2	 + U_3 * alt_3statement3	 + U_4 * alt_3statement4	 + U_5 * alt_3statement5	 + U_6 * alt_3statement6	 + U_7 * alt_3statement7	 + U_8 * alt_3statement8	 + U_9 * alt_3statement9	 + U_10 * alt_3statement10	 + U_11 * alt_3statement11	 + U_12 * alt_3statement12	 + U_13 * alt_3statement13	 + U_14 * alt_3statement14	 + U_15 * alt_3statement15	 + U_16 * alt_3statement16	 + U_17 * alt_3statement17	 + U_18 * alt_3statement18	 + U_19 * alt_3statement19	 + U_20 * alt_3statement20	 + U_21 * alt_3statement21	 + U_22 * alt_3statement22	 + U_23 * alt_3statement23	 + U_24 * alt_3statement24	 + U_25 * alt_3statement25	 + U_26 * alt_3statement26	 + U_27 * alt_3statement27	 + U_28 * alt_3statement28	 + U_29 * alt_3statement29	 + U_30 * alt_3statement30	 + U_31 * alt_3statement31	 ","\n")
     cat("     v4	= 	asc_4  + U_1 * alt_4statement1	 + U_2 * alt_4statement2	 + U_3 * alt_4statement3	 + U_4 * alt_4statement4	 + U_5 * alt_4statement5	 + U_6 * alt_4statement6	 + U_7 * alt_4statement7	 + U_8 * alt_4statement8	 + U_9 * alt_4statement9	 + U_10 * alt_4statement10	 + U_11 * alt_4statement11	 + U_12 * alt_4statement12	 + U_13 * alt_4statement13	 + U_14 * alt_4statement14	 + U_15 * alt_4statement15	 + U_16 * alt_4statement16	 + U_17 * alt_4statement17	 + U_18 * alt_4statement18	 + U_19 * alt_4statement19	 + U_20 * alt_4statement20	 + U_21 * alt_4statement21	 + U_22 * alt_4statement22	 + U_23 * alt_4statement23	 + U_24 * alt_4statement24	 + U_25 * alt_4statement25	 + U_26 * alt_4statement26	 + U_27 * alt_4statement27	 + U_28 * alt_4statement28	 + U_29 * alt_4statement29	 + U_30 * alt_4statement30	 + U_31 * alt_4statement31	 ","\n")
     cat("     v5	= 	asc_5  + U_1 * alt_5statement1	 + U_2 * alt_5statement2	 + U_3 * alt_5statement3	 + U_4 * alt_5statement4	 + U_5 * alt_5statement5	 + U_6 * alt_5statement6	 + U_7 * alt_5statement7	 + U_8 * alt_5statement8	 + U_9 * alt_5statement9	 + U_10 * alt_5statement10	 + U_11 * alt_5statement11	 + U_12 * alt_5statement12	 + U_13 * alt_5statement13	 + U_14 * alt_5statement14	 + U_15 * alt_5statement15	 + U_16 * alt_5statement16	 + U_17 * alt_5statement17	 + U_18 * alt_5statement18	 + U_19 * alt_5statement19	 + U_20 * alt_5statement20	 + U_21 * alt_5statement21	 + U_22 * alt_5statement22	 + U_23 * alt_5statement23	 + U_24 * alt_5statement24	 + U_25 * alt_5statement25	 + U_26 * alt_5statement26	 + U_27 * alt_5statement27	 + U_28 * alt_5statement28	 + U_29 * alt_5statement29	 + U_30 * alt_5statement30	 + U_31 * alt_5statement31	 ","\n")
     cat("     v6	= 	asc_6  + U_1 * alt_6statement1	 + U_2 * alt_6statement2	 + U_3 * alt_6statement3	 + U_4 * alt_6statement4	 + U_5 * alt_6statement5	 + U_6 * alt_6statement6	 + U_7 * alt_6statement7	 + U_8 * alt_6statement8	 + U_9 * alt_6statement9	 + U_10 * alt_6statement10	 + U_11 * alt_6statement11	 + U_12 * alt_6statement12	 + U_13 * alt_6statement13	 + U_14 * alt_6statement14	 + U_15 * alt_6statement15	 + U_16 * alt_6statement16	 + U_17 * alt_6statement17	 + U_18 * alt_6statement18	 + U_19 * alt_6statement19	 + U_20 * alt_6statement20	 + U_21 * alt_6statement21	 + U_22 * alt_6statement22	 + U_23 * alt_6statement23	 + U_24 * alt_6statement24	 + U_25 * alt_6statement25	 + U_26 * alt_6statement26	 + U_27 * alt_6statement27	 + U_28 * alt_6statement28	 + U_29 * alt_6statement29	 + U_30 * alt_6statement30	 + U_31 * alt_6statement31	 ","\n")
     cat("     v7	= 	asc_7  + U_1 * alt_7statement1	 + U_2 * alt_7statement2	 + U_3 * alt_7statement3	 + U_4 * alt_7statement4	 + U_5 * alt_7statement5	 + U_6 * alt_7statement6	 + U_7 * alt_7statement7	 + U_8 * alt_7statement8	 + U_9 * alt_7statement9	 + U_10 * alt_7statement10	 + U_11 * alt_7statement11	 + U_12 * alt_7statement12	 + U_13 * alt_7statement13	 + U_14 * alt_7statement14	 + U_15 * alt_7statement15	 + U_16 * alt_7statement16	 + U_17 * alt_7statement17	 + U_18 * alt_7statement18	 + U_19 * alt_7statement19	 + U_20 * alt_7statement20	 + U_21 * alt_7statement21	 + U_22 * alt_7statement22	 + U_23 * alt_7statement23	 + U_24 * alt_7statement24	 + U_25 * alt_7statement25	 + U_26 * alt_7statement26	 + U_27 * alt_7statement27	 + U_28 * alt_7statement28	 + U_29 * alt_7statement29	 + U_30 * alt_7statement30	 + U_31 * alt_7statement31	 ","\n")
     cat("     v8	= 	asc_8  + U_1 * alt_8statement1	 + U_2 * alt_8statement2	 + U_3 * alt_8statement3	 + U_4 * alt_8statement4	 + U_5 * alt_8statement5	 + U_6 * alt_8statement6	 + U_7 * alt_8statement7	 + U_8 * alt_8statement8	 + U_9 * alt_8statement9	 + U_10 * alt_8statement10	 + U_11 * alt_8statement11	 + U_12 * alt_8statement12	 + U_13 * alt_8statement13	 + U_14 * alt_8statement14	 + U_15 * alt_8statement15	 + U_16 * alt_8statement16	 + U_17 * alt_8statement17	 + U_18 * alt_8statement18	 + U_19 * alt_8statement19	 + U_20 * alt_8statement20	 + U_21 * alt_8statement21	 + U_22 * alt_8statement22	 + U_23 * alt_8statement23	 + U_24 * alt_8statement24	 + U_25 * alt_8statement25	 + U_26 * alt_8statement26	 + U_27 * alt_8statement27	 + U_28 * alt_8statement28	 + U_29 * alt_8statement29	 + U_30 * alt_8statement30	 + U_31 * alt_8statement31	 ","\n")
     cat("     v9	= 	asc_9  + U_1 * alt_9statement1	 + U_2 * alt_9statement2	 + U_3 * alt_9statement3	 + U_4 * alt_9statement4	 + U_5 * alt_9statement5	 + U_6 * alt_9statement6	 + U_7 * alt_9statement7	 + U_8 * alt_9statement8	 + U_9 * alt_9statement9	 + U_10 * alt_9statement10	 + U_11 * alt_9statement11	 + U_12 * alt_9statement12	 + U_13 * alt_9statement13	 + U_14 * alt_9statement14	 + U_15 * alt_9statement15	 + U_16 * alt_9statement16	 + U_17 * alt_9statement17	 + U_18 * alt_9statement18	 + U_19 * alt_9statement19	 + U_20 * alt_9statement20	 + U_21 * alt_9statement21	 + U_22 * alt_9statement22	 + U_23 * alt_9statement23	 + U_24 * alt_9statement24	 + U_25 * alt_9statement25	 + U_26 * alt_9statement26	 + U_27 * alt_9statement27	 + U_28 * alt_9statement28	 + U_29 * alt_9statement29	 + U_30 * alt_9statement30	 + U_31 * alt_9statement31	 ","\n")
     cat("     v10	= 	asc_10 + U_1 * alt_10statement1	 + U_2 * alt_10statement2	 + U_3 * alt_10statement3	 + U_4 * alt_10statement4	 + U_5 * alt_10statement5	 + U_6 * alt_10statement6	 + U_7 * alt_10statement7	 + U_8 * alt_10statement8	 + U_9 * alt_10statement9	 + U_10 * alt_10statement10	 + U_11 * alt_10statement11	 + U_12 * alt_10statement12	 + U_13 * alt_10statement13	 + U_14 * alt_10statement14	 + U_15 * alt_10statement15	 + U_16 * alt_10statement16	 + U_17 * alt_10statement17	 + U_18 * alt_10statement18	 + U_19 * alt_10statement19	 + U_20 * alt_10statement20	 + U_21 * alt_10statement21	 + U_22 * alt_10statement22	 + U_23 * alt_10statement23	 + U_24 * alt_10statement24	 + U_25 * alt_10statement25	 + U_26 * alt_10statement26	 + U_27 * alt_10statement27	 + U_28 * alt_10statement28	 + U_29 * alt_10statement29	 + U_30 * alt_10statement30	 + U_31 * alt_10statement31	 ","\n")
     cat("     v11	= 	asc_11 + U_1 * alt_11statement1	 + U_2 * alt_11statement2	 + U_3 * alt_11statement3	 + U_4 * alt_11statement4	 + U_5 * alt_11statement5	 + U_6 * alt_11statement6	 + U_7 * alt_11statement7	 + U_8 * alt_11statement8	 + U_9 * alt_11statement9	 + U_10 * alt_11statement10	 + U_11 * alt_11statement11	 + U_12 * alt_11statement12	 + U_13 * alt_11statement13	 + U_14 * alt_11statement14	 + U_15 * alt_11statement15	 + U_16 * alt_11statement16	 + U_17 * alt_11statement17	 + U_18 * alt_11statement18	 + U_19 * alt_11statement19	 + U_20 * alt_11statement20	 + U_21 * alt_11statement21	 + U_22 * alt_11statement22	 + U_23 * alt_11statement23	 + U_24 * alt_11statement24	 + U_25 * alt_11statement25	 + U_26 * alt_11statement26	 + U_27 * alt_11statement27	 + U_28 * alt_11statement28	 + U_29 * alt_11statement29	 + U_30 * alt_11statement30	 + U_31 * alt_11statement31	 ","\n")
     cat("     v12	= 	asc_12 + U_1 * alt_12statement1	 + U_2 * alt_12statement2	 + U_3 * alt_12statement3	 + U_4 * alt_12statement4	 + U_5 * alt_12statement5	 + U_6 * alt_12statement6	 + U_7 * alt_12statement7	 + U_8 * alt_12statement8	 + U_9 * alt_12statement9	 + U_10 * alt_12statement10	 + U_11 * alt_12statement11	 + U_12 * alt_12statement12	 + U_13 * alt_12statement13	 + U_14 * alt_12statement14	 + U_15 * alt_12statement15	 + U_16 * alt_12statement16	 + U_17 * alt_12statement17	 + U_18 * alt_12statement18	 + U_19 * alt_12statement19	 + U_20 * alt_12statement20	 + U_21 * alt_12statement21	 + U_22 * alt_12statement22	 + U_23 * alt_12statement23	 + U_24 * alt_12statement24	 + U_25 * alt_12statement25	 + U_26 * alt_12statement26	 + U_27 * alt_12statement27	 + U_28 * alt_12statement28	 + U_29 * alt_12statement29	 + U_30 * alt_12statement30	 + U_31 * alt_12statement31	 ","\n")
     cat("     ","\n")
     cat("     ","\n")
     cat("     v1     <- exp(v1)","\n")
     cat("     v2     <- exp(v2)","\n")
     cat("     v3     <- exp(v3)","\n")
     cat("     v4     <- exp(v4)","\n")
     cat("     v5     <- exp(v5)","\n")
     cat("     v6     <- exp(v6)","\n")
     cat("     v7     <- exp(v7)","\n")
     cat("     v8     <- exp(v8)","\n")
     cat("     v9     <- exp(v9)","\n")
     cat("     v10    <- exp(v10)","\n")
     cat("     v11    <- exp(v11)","\n")
     cat("     v12    <- exp(v12)","\n")
     cat("     ","\n")
     cat("  ####################################################################","\n")
     cat("  # You should not need to change anything below this line","\n")
     cat("  # use of the data.table package to speed up computation time","\n")
     cat("     ","\n")
     cat("     p.temp <- data.table(gIDS, p=( choice1 * v1 + choice2 * v2 + choice3 * v3 + choice4 * v4 + choice5 * v5 + choice6 * v6 + choice7 * v7	+ choice8 * v8 + choice9 * v9 + choice10 * v10 + choice11 * v11 + choice12 * v12 ) / ( v1 + v2 + v3 + v4 + v5 + v6 + v7 + v8 + v9 + v10 + v11 + v12))","\n")
     cat("     setkey(p.temp,gIDS)","\n")
     cat("     ","\n")
     cat("     p0     <- p.temp[,prod(p),by=gIDS]$V1","\n")
     cat("     ","\n")
     cat("     p0     <- is.na(p0)*0 + (!is.na(p0))*p0","\n")
     cat("     ","\n")
     cat("     return(p0)","\n")
     cat("}","\n")
     sink()
}

