createBasicMNLFile <- function()
{
     sink("ExampleBasicMNLFile.R",append=F)
     cat("# ------------------","\n")
     cat("# Code for a Multinomial Logit Model with Random Coefficients","\n")
     cat("# ","\n")
     cat("# Jeff Dumont","\n")
     cat("#","\n")
     cat("# Requires","\n")
     cat("# data.table package","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("library(RSGHB)","\n")
     cat("library(data.table)","\n")
     cat("","\n")
     cat("createGlobalVariables()","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# Global Settings","\n")
     cat("# ------------------","\n")
     cat("setwd(\"C:/Work/Code/HB/Examples/Basic Example - MNL\" # working directory","\n")
     cat("","\n")
     cat("modelname <- \"Base\"		# used for output","\n")
     cat("","\n")
     cat("gSeed <- 0","\n")
     cat("","\n")
     cat("	          # number of significant digits","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# DATA PREPARATION","\n")
     cat("# ------------------","\n")
     cat("","\n")
     cat("# assumes that respondents are identified with a ID column","\n")
     cat("# also assumes that the data is sorted by respondent then experiment","\n")
     cat("choicedata <- read.table(\"ChoiceData.dat\",sep=\"\t\",header=T)","\n")
     cat("","\n")
     cat("# Specify any variables here that you'd like to use in the","\n")
     cat("# utility equations in the likelihood function below","\n")
     cat("# These can be any variables within the data or transformations of","\n")
     cat("# those variables","\n")
     cat("TT1     <- choicedata$tt1","\n")
     cat("TT2     <- choicedata$tt2","\n")
     cat("TOLL2   <- choicedata$toll2","\n")
     cat("","\n")
     cat("# The choice vectors","\n")
     cat("# Dummying coding the choice vector allows for easier coding of the ","\n")
     cat("# the likelihood calculations. So we will have one column for each ","\n")
     cat("# alternative in the design","\n")
     cat("choice1    <- (choicedata$Choice==1)","\n")
     cat("choice2    <- (choicedata$Choice==2)","\n")
     cat("","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# MODEL SPECIFICATION ","\n")
     cat("# ------------------","\n")
     cat("# Names for the variables","\n")
     cat("# if none specified use c()","\n")
     cat("# there are two types of variables you can specify - random or fixed","\n")
     cat("# random coefficients are assumed to differ from one respondent to the next","\n")
     cat("# fixed coefficients do not vary accross individuals in your dataset","\n")
     cat(" ","\n")
     cat("# Random Variables","\n")
     cat("gVarNamesNormal <- c(\"ASC1\",\"BTime\",\"BCost\")","\n")
     cat(" ","\n")
     cat("# Fixed Variables","\n")
     cat("gVarNamesFixed <- c()","\n")
     cat("","\n")
     cat("# For each variable, specify the distribution for its coefficient","\n")
     cat("# The options are:","\n")
     cat("# 1. normal","\n")
     cat("# 2. log-nomal","\n")
     cat("# 3. negative log-normal","\n")
     cat("# 4. normal with all values below zero massed at zero","\n")
     cat("# 5. Johnson SB with a specified min and max","\n")
     cat("# gDIST must have an entry for each value in gVarNamesNormal","\n")
     cat("","\n")
     cat("gDIST <- c(1,1,1)","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# STARTING VALUES","\n")
     cat("# ------------------","\n")
     cat("FC <- c()                  # for the fixed coefficients","\n")
     cat("","\n")
     cat("svN <- c(0,0,0)            # for the random coefficients","\n")
     cat("                           # The selection of the mean here is important when working with non-normal distributions","\n")
     cat("# ------------------","\n")
     cat("# ITERATION SETTINGS","\n")
     cat("# ------------------","\n")
     cat("gNCREP    <- 20000  	  # Number of iterations to use prior to convergence","\n")
     cat("gNEREP    <- 10000 	       # Number of iterations to keep for averaging after convergence has been reached","\n")
     cat("gNSKIP    <- 1			  # Number of iterations to do in between retaining draws for averaging","\n")
     cat("gINFOSKIP <- 250           # How frequently to print info about the iteration process","\n")
     cat("","\n")
     cat("","\n")
     cat("# ------------------","\n")
     cat("# likelihood","\n")
     cat("# USE:     Calculates the likelihood of choice | B","\n")
     cat("#          Returns individual-specific likelihood values","\n")
     cat("# NOTES:   This is where the bulk of the computation resides so coding this efficiently","\n")
     cat("#	      is essential to reducing run time.","\n")
     cat("# ------------------","\n")
     cat("likelihood <- function(fc,b)","\n")
     cat("{","\n")
     cat("","\n")
     cat("  p0     <- matrix(0,nrow=gNP,ncol=1)","\n")
     cat("  ","\n")
     cat("  C      <- trans(b)","\n")
     cat("	","\n")
     cat("  # creates vectors of individual-specific coefficients","\n")
     cat("  cc = 1","\n")
     cat("  ASC1   <- C[gIDS,cc];cc=cc+1","\n")
     cat("  Btime  <- C[gIDS,cc];cc=cc+1","\n")
     cat("  Btoll  <- C[gIDS,cc];cc=cc+1  ","\n")
     cat("  ","\n")
     cat("  v1 = ASC1       + Btime * TT1                   ","\n")
     cat("  v2 =              Btime * TT2 + Btoll * TOLL2   ","\n")
     cat(" ","\n")
     cat("  p = (exp(v1)*choice1 + exp(v2)*choice2) / (exp(v1) + exp(v2))","\n")
     cat("  ","\n")
     cat("  ","\n")
     cat("  ####################################################################","\n")
     cat("  # You should not need to change anything below this line","\n")
     cat("  # use of the data.table package to speed up computation time","\n")
     cat("  p <- as.vector(p) # need to convert to a vector so data.table","\n")
     cat("                       # returns the likelihood with the right level of precision.","\n")
     cat(" ","\n")
     cat("  p.temp <- data.table(gIDS,p)","\n")
     cat("  setkey(p.temp,gIDS)","\n")
     cat("	","\n")
     cat("  p0     <- p.temp[,prod(p),by=gIDS]$V1","\n")
     cat("		","\n")
     cat("  p0     <- replace(p0,is.nan(p0),1e-32)","\n")
     cat("	","\n")
     cat("  return(p0)","\n")
     cat("}","\n")
     sink()
}
    